import type { SqlTableName } from '@/platform/db/schema/ownership'

export type DestructiveAdapterVerb = 'select' | 'insert' | 'update' | 'delete'

export type DestructiveAdapterMethodManifest = Readonly<
  Record<DestructiveAdapterVerb, readonly SqlTableName[]>
>

/**
 * Exact temporary Stage 3 authority surface for Data Portability's scoped
 * destructive adapter. Lists are lexical for deterministic review; execution
 * order remains the adapter's referential-integrity order.
 */
export const temporaryDestructiveAdapterManifest = {
  invalidatePreviewAfterDenial: {
    select: [],
    insert: [],
    update: [],
    delete: ['deletion_plan'],
  },
  executeSubjectDeletion: {
    select: [
      'account',
      'adjustment_decision',
      'adjustment_decision_invalidation',
      'athlete_equipment',
      'athlete_profile',
      'athlete_training_day',
      'audit_event',
      'deletion_plan',
      'exercise_prescription',
      'future_load_explanation_cache',
      'member_reset_state',
      'performed_set',
      'performed_set_correction',
      'planned_workout',
      'program',
      'program_revision',
      'program_revision_invalidation',
      'program_revision_lineage',
      'safety_hold',
      'safety_hold_resolution',
      'session',
      'session_exercise',
      'session_feedback',
      'session_feedback_correction',
      'set_prescription',
      'strength_baseline',
      'training_command_receipt',
      'training_fact_correction',
      'user',
      'verification',
      'workout_session',
    ],
    insert: ['deletion_tombstone'],
    update: [],
    delete: [
      'account',
      'adjustment_decision_invalidation',
      'athlete_equipment',
      'athlete_profile',
      'athlete_training_day',
      'audit_event',
      'deletion_plan',
      'future_load_explanation_cache',
      'member_reset_state',
      'performed_set_correction',
      'program',
      'program_revision_invalidation',
      'program_revision_lineage',
      'safety_hold',
      'safety_hold_resolution',
      'session',
      'session_feedback_correction',
      'strength_baseline',
      'training_command_receipt',
      'training_fact_correction',
      'user',
      'verification',
      'workout_session',
    ],
  },
  executeInstanceReset: {
    select: [
      'account',
      'adjustment_decision',
      'adjustment_decision_invalidation',
      'athlete_equipment',
      'athlete_profile',
      'athlete_training_day',
      'audit_event',
      'content_release_revocation',
      'deletion_plan',
      'destructive_reauthentication_state',
      'exercise_prescription',
      'future_load_explanation_cache',
      'installation_state',
      'member_reset_state',
      'performed_set',
      'performed_set_correction',
      'planned_workout',
      'program',
      'program_revision',
      'program_revision_invalidation',
      'program_revision_lineage',
      'safety_hold',
      'safety_hold_resolution',
      'session',
      'session_exercise',
      'session_feedback',
      'session_feedback_correction',
      'set_prescription',
      'strength_baseline',
      'training_command_receipt',
      'training_fact_correction',
      'user',
      'verification',
      'web_recovery_rate_limit_bucket',
      'workout_session',
    ],
    insert: ['deletion_tombstone'],
    update: ['installation_state'],
    delete: [
      'account',
      'adjustment_decision',
      'adjustment_decision_invalidation',
      'athlete_equipment',
      'athlete_profile',
      'athlete_training_day',
      'audit_event',
      'content_release_revocation',
      'deletion_plan',
      'destructive_reauthentication_state',
      'exercise_prescription',
      'future_load_explanation_cache',
      'member_reset_state',
      'performed_set',
      'performed_set_correction',
      'planned_workout',
      'program',
      'program_revision',
      'program_revision_invalidation',
      'program_revision_lineage',
      'safety_hold',
      'safety_hold_resolution',
      'session',
      'session_exercise',
      'session_feedback',
      'session_feedback_correction',
      'set_prescription',
      'strength_baseline',
      'training_command_receipt',
      'training_fact_correction',
      'user',
      'verification',
      'web_recovery_rate_limit_bucket',
      'workout_session',
    ],
  },
} as const satisfies Record<string, DestructiveAdapterMethodManifest>

export type TemporaryDestructiveAdapterMethod =
  keyof typeof temporaryDestructiveAdapterManifest
